package vn.edu.iuh.fit.common.command;

public enum ActionType {
    LOGIN,
    FILTER_SCHEDULE,
    CREATE_SCHEDULE,

    CREATE_EMPLOYEE,
    CREATE_EMPLOYEE_ACCOUNT,
    DELETE_EMPLOYEE,
    FIND_ALL_EMPLOYEES,
    RESET_EMPLOYEE_PASSWORD,

    GET_STATISTICS,

    FIND_ALL_TRAINS,
    FIND_TRAIN_BY_CODE,
    FIND_UNASSIGNED_CARRIAGES,
    CREATE_TRAIN,
    CREATE_CARRIAGE,
    UPDATE_TRAIN_CARRIAGES,
    UPDATE_TRAIN_STATUS
}
