package vn.edu.iuh.fit.common.command;

public enum ActionType {
    LOGIN,
    FILTER_SCHEDULE,
    CREATE_SCHEDULE,
    UPDATE_SCHEDULE,
    GENERATE_SCHEDULES,
    FIND_SCHEDULE_DETAILS,
    UPDATE_SCHEDULE_DETAIL_PRICES,

    CREATE_EMPLOYEE,
    CREATE_EMPLOYEE_ACCOUNT,
    DELETE_EMPLOYEE,
    FIND_ALL_EMPLOYEES,
    RESET_EMPLOYEE_PASSWORD,

    GET_STATISTICS,

    SEARCH_TICKETS_FOR_RETURN,
    PREVIEW_RETURN_TICKETS,
    CONFIRM_RETURN_TICKETS,
    GET_REFUND_RECEIPT,

    SEARCH_TICKETS_FOR_EXCHANGE,
    PREVIEW_EXCHANGE_TICKETS,
    EXCHANGE_TICKET,

    FIND_ALL_TRAINS,
    FIND_TRAIN_BY_CODE,
    FIND_UNASSIGNED_CARRIAGES,
    CREATE_TRAIN,
    CREATE_CARRIAGE,
    UPDATE_TRAIN_CARRIAGES,
    UPDATE_TRAIN_STATUS,

    FIND_ALL_STATIONS,
    FIND_ALL_ROUTES,
    SEARCH_ROUTES,
    FIND_ROUTE_BY_ID,
    CREATE_ROUTE,
    UPDATE_ROUTE,
    DELETE_ROUTE,
    PROMOTE_ROUTE,
    DISABLE_ROUTE,
    FIND_ROUTE_STOPS_BY_ROUTE,
    CREATE_ROUTE_STOP,
    UPDATE_ROUTE_STOP,
    DELETE_ROUTE_STOP,

    PUBLISH_OR_DISABLE_SCHEDULE,

    SEARCH_CUSTOMERS,
    CREATE_CUSTOMER,
    UPDATE_CUSTOMER,
    DELETE_CUSTOMER,
    GET_CUSTOMER_HISTORY,

    SEARCH_SCHEDULES_FOR_SALE,
    GET_SEATMAP_FOR_SCHEDULE,
    HOLD_SEATS_FOR_SALE,
    RELEASE_HELD_SEATS_FOR_SALE,
    CREATE_PAYMENT_ORDER,
    GET_PAYMENT_ORDER_STATUS,
    CONFIRM_PAYMENT_ORDER,
    CONFIRM_INTERNAL_PAYMENT,
    CREATE_SALE_TRANSACTION

}
